---
title: "State corrections"
output: html_document
---

```{r setup, include=FALSE}
library(zookeeper)
library(covidcast)
library(tidyverse)
library(lubridate)
df <- suppressMessages(
  covidcast_signals(
    "jhu-csse",
    c("deaths_incidence_num","confirmed_incidence_num"),
    start_day = Sys.Date() - duration(6, "months"),
    geo_type = "state"
  )
)

aad <- zookeeper::make_state_corrector(
  manual_flags = tibble::tibble(data_source = "jhu-csse", 
                        signal = c(rep("deaths_incidence_num", 3),
                                   "confirmed_incidence_num",
                                   ## from JHU-CSSE notes 2021-04-17, 2021-04-18
                                   "deaths_incidence_num",
                                   "deaths_incidence_num",
                                   "confirmed_incidence_num",
                                   "confirmed_incidence_num"
                                   ),
                        geo_value = c("va","ky","ok","ok",
                                      ## from JHU-CSSE notes 2021-04-17, 2021-04-18
                                      "ak","mi","mo","al"),
                        time_value = list(
                          seq(lubridate::ymd("2021-02-21"), lubridate::ymd("2021-03-04"), by = 1),
                          lubridate::ymd(c("2021-03-18","2021-03-19")),
                          lubridate::ymd("2021-04-07"), 
                          lubridate::ymd("2021-04-07"),
                          ## from JHU-CSSE notes 2021-04-17, 2021-04-18
                          lubridate::ymd("2021-04-15"),
                          lubridate::ymd(c("2021-04-01", "2021-04-03", "2021-04-06", "2021-04-08", "2021-04-10", "2021-04-13", "2021-04-15", "2021-04-17")),
                          lubridate::ymd("2021-04-17"),
                          lubridate::ymd("2021-04-13")
                          ),
                        max_lag = c(rep(90, 4),
                                    ## from JHU-CSSE notes 2021-04-17, 2021-04-18
                                    75, 150, 150, 180
                          )
                        ),
  corrections_db_path = "state-corrections.RDS")
corrected <- aad(df)
corrected <- readRDS("state-corrections.RDS") %>%
  filter(time_value > Sys.Date() - duration(3, "months")) %>%
  select(-data_source) %>%
  pivot_longer(value:corrected)
```

```{r, echo = FALSE, fig.height = 120, fig.width = 10, dev="CairoSVG"}
corrected %>% 
  ggplot(aes(time_value)) + geom_line(aes(y=value, color=name)) +
  geom_point(data = filter(corrected, flag | special_flag, name == "value"), 
             aes(y = value), color="orange") +
  facet_wrap(~signal + geo_value , scales = "free", ncol = 3) +
  theme_bw() + xlab("") + ylab("") +
  scale_color_viridis_d(begin=.25, end=.75) + 
  theme(legend.position = "none") +
  scale_x_date(date_breaks = "months" , date_labels = "%b")
```



