# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - 'main'
      - 'develop'
    paths:
      - 'forecasters/strawman/**'
  pull_request:
    branches:
      - 'main'
      - 'develop'
    paths:
      - 'forecasters/strawman/**'


name: check-fcast-strawman

defaults:
  run:
    working-directory: 'forecasters/strawman'

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
